include:
  # QWERTY Dongle
  - board: nice_nano_v2
    shield: charybdis_left
    keymap: qwerty
    format: dongle
    artifact-name: charybdis_qwerty_dongle_left
    
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    format: dongle
    cmake-args: "-DZMK_EXTRA_MODULES='/__w/charybdis_zmk/charybdis_zmk;/tmp/zmk-config/zmk-pmw3610-driver'"
    artifact-name: charybdis_qwerty_dongle_right
    
  - board: xiao_ble
    shield: charybdis_dongle prospector_adapter
    keymap: qwerty
    format: dongle
    cmake-args: "-DBOARD_ROOT=/tmp/zmk-config/prospector-zmk-module"
    artifact-name: charybdis_qwerty_dongle_display

  # Firmware Reset
  - board: nice_nano_v2
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_nano_v2
    
  - board: xiao_ble
    shield: settings_reset
    format: reset
    cmake-args: "-DBOARD_ROOT=/tmp/zmk-config/prospector-zmk-module"
    artifact-name: firmware_reset_xiao_ble